Add failure, if message is not being consumed properly.

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -92,4 +92,12 @@ jobs:
 
       - name: Consume message from Kafka topic
         run: |
-             kubectl exec $(kubectl get pods -n kafka -l app=kafka-consumer -o jsonpath='{.items[0].metadata.name}') -n kafka -- /bin/bash -c "kafka-console-consumer.sh --topic test-topic --bootstrap-server kafka-svc.kafka:9092 --from-beginning  --max-messages 1"
+              MESSAGE=$(kubectl exec $(kubectl get pods -n kafka -l app=kafka-consumer -o jsonpath='{.items[0].metadata.name}') -n kafka -- /bin/bash -c "kafka-console-consumer.sh --topic test-topic --bootstrap-server kafka-svc.kafka:9092 --from-beginning  --max-messages 1")
+              echo "Consumed message: $MESSAGE"
+
+              if [ "$MESSAGE" == "Hello, Kafka!" ]; then
+                echo "✅ Message consumed successfully"
+              else
+                echo "❌ Message consumption failed"
+                exit 1
+              fi
